name: Build Windows

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # Run on tag pushes too
  pull_request:
    branches:
      - main
  # Allow manual triggering
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: true  # Ensure submodules are checked out

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Match your development environment

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install Pillow  # Required for icon creation

    - name: Run Windows build script
      run: |
        python build/windows/build_windows.py

    - name: List build output
      run: |
        dir dist\windows

    - name: Create ZIP archive
      run: |
        powershell Compress-Archive -Path "dist\windows\Resolume Composition Converter" -DestinationPath "dist\Resolume-Composition-Converter-Windows.zip" -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Resolume-Composition-Converter-Windows
        path: dist\Resolume-Composition-Converter-Windows.zip

    # Create a GitHub Release when a tag is pushed
    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: Windows Build ${{ github.ref_name }}
        files: dist\Resolume-Composition-Converter-Windows.zip
        body: |
          Windows build of Resolume Composition Converter version ${{ github.ref_name }}.
          
          ## Installation
          1. Download the ZIP file
          2. Extract to your desired location
          3. Run "Resolume Composition Converter.exe"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}